### ISSUE TITLE
Calculate qualitative severity rating

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#11]
Sometimes the user does not need the exact numeric score of a vector, but instead he wants a qualitative rating.
Those ratings are specified in section `5. Qualitative Severity Rating Scale` of the following document: https://www.first.org/cvss/v3.0/specification-document

Basically, we just need a function to map the score to the qualitative rating defined in the following table:

Rating | CVSS Score
-|-
None | 0.0
Low | 0.1 - 3.9
Medium | 4.0 - 6.9
High | 7.0 - 8.9
Critical | 9.0 - 10.0

**Comment by m1ga** [comment]
@Fubinator Happy to help here!

**Comment by Fubinator** [comment]
Go ahead @m1ga. If you have any questions feel free to ask.
