### ISSUE TITLE
Function to get an object of the vector's metrics

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#20]
Currently we split the vector in the getScore() function and create an object with the abbreviations as key and the vector values as value:
https://github.com/turingpointde/cvss.js/blob/main/lib/cvss.js#L16-L22

We should refactor this into a separate function and make it available to the public API.

It is useful to provide this function to the user. In the future it is imaginable that even more information will be generated by this function.

**Comment by vivek32ta** [comment]
Hi @Fubinator 

I'd love to take this up

**Comment by Fubinator** [comment]
@vivek32ta sure, go ahead! If you have any questions feel free to ask.

**Comment by vivek32ta** [comment]
Just to clarify... do you want to make getScore() available on a public endpoint as it is?

**Comment by Fubinator** [comment]
`getScore()` is already public. What I want is a function (e.g. `getVectorObject()`) that a) the end user can use for his own purposes and b) we can use to calculate scores.

**Comment by vivek32ta** [comment]
Got it. Thanks! 

:)

**Comment by vivek32ta** [comment]
Hey @Fubinator 

I've made `getVectorObject()` a separate method and called it within `getScore()`.

To make it publicly available, I just have to add an argument [here](https://github.com/turingpointde/cvss.js/blob/a92b2ad536789eae8892bae775df29a52f338b35/lib/cvss.js#L100) right?

Or do I also need to change something else?

**Comment by Fubinator** [comment]
Yes, that's right. It would be nice if you could write some test cases for the function.
