### ISSUE TITLE
Check if vector is malformed

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#21]
We should test if vectors meet the standards of the specification. This should prevent the library to throw unexpected errors. For this to work we need a function that tests the following:

1. Are all required metrics included in the vector? 
2. Are there any metrics that are not in the specification?
3. Do all metrics have only possible values? 

For refrence which metrics are required and so on you can take a look [here](https://www.first.org/cvss/v3.0/specification-document#Vector-String).

It might be an idea to make this function available to the end user to quickly test if a vector is valid.

**Comment by jackson541** [comment]
I'm really enjoying the project, as I'm already finishing the other issue, can I keep this one too?

**Comment by Fubinator** [comment]
Yes, sure @jackson541. Please have a look at https://github.com/turingpointde/cvss.js/issues/9#issuecomment-702807593 before though regarding your fork.

**Comment by Fubinator** [comment]
@jackson541 FYI: There is already a JS implementation for this where you could have a look: 

https://www.first.org/cvss/calculator/cvsscalc30.js
https://www.first.org/cvss/v3.0/use-design#techdesign

The checks to determine if the vector is malformed are really bloated though, so just consider writing your own implementation. I think it would be way shorter with regular expressions (even though regular expressions are generally quite slow, but I think that does not matter in this case).

**Comment by jackson541** [comment]
Nice, so i'm going to create with regex

**Comment by jackson541** [comment]
@Fubinator is it necessary that the arguments of the vector are always in the same order (AV:N/AC:H/PR:L/UI:R...) or can they be in another order (AC:H/PR:L/AV:N/UI:R...)?

**Comment by Fubinator** [comment]
@jackson541 
From the spec: "Metrics may be specified in any order in a vector string, though Table 15 . shows the preferred order."

So the order does not really matter.

One thing that I just discovered and have not included in the issue: A vector string must not include the same metric more than once."
So we have to make sure every vector exists only once.

**Comment by jackson541** [comment]
@Fubinator Well observed, I will work on it. Thank you!
