### ISSUE TITLE
Get a complex object describing the vector

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#25]
Sometimes it's useful to get an object with a whole lot of information. E.g. for displaying the vector in the following ways:
![image](https://user-images.githubusercontent.com/16110028/94950030-34ce7e00-04e2-11eb-9bfe-c66355ea5392.png)

To save the user effort, we can return a complex object with some more detailed information. An example object could look like this:

```js
{
  version: 3.0, // this is going to be implemented with #8
  metrics: {
    AV: {
      name: "Attack Vector",
      abbr: "AV",
      fullName: "Attack Vector (AV)",
      value: "Network",
      valueAbbr: "N"
    },
    AC: {
      name: "Attack Complexity",
      abbr: "AC",
      fullName: "Attack Complexity (AC)",
      value: "Low",
      valueAbbr: "L"
    }
    ...
  }
}
```

**Comment by jasbindar-singh** [comment]
So, basically a function similar to getVectorObject() that will give out a more detailed object, is it?

**Comment by Fubinator** [comment]
Exactly @jasbindar-singh

**Comment by jasbindar-singh** [comment]
I will work on it

**Comment by Fubinator** [comment]
Alright, go for it! If you have any questions feel free to ask.
