### ISSUE TITLE
Add Test Setup

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#3]
We need a test environment with some initial tests and a GitHub action.

**Comment by Wekananda** [comment]
Hello, can you assign me this issue?

**Comment by Fubinator** [comment]
Of course @Wekananda. If you have any questions feel free to ask.

**Comment by Wekananda** [comment]
#13 Okay, already add the github actions.

**Comment by Fubinator** [comment]
Yes i see @Wekananda the actions fail because we do not have an actual test setup. Do you want to implement this? If not I can take over.
I suggest using jest and putting the test files in a designated `test` folder.

**Comment by Wekananda** [comment]
Sorry,
I still not experienced to create unit testing. I think it's better you handling this.

**Comment by Fubinator** [comment]
Alright, no worries, thanks for your contribution!
