### ISSUE TITLE
GitHub Action to builld automatically

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#35]
With #34 we can build the project locally. What would be useful now is a Github action that builds the library automatically and updates the repo if changes are merged into main.

We discussed splitting this in #31. @amstr4d do you want to take this?

**Comment by amstr4d** [comment]
Yes I can take it !

**Comment by Fubinator** [comment]
Alright,  go ahead @amstr4d. I think you should wait for #34 to get merged though,  right?

**Comment by amstr4d** [comment]
Yes, I will just create the PR in order to talk about it.
