### ISSUE TITLE
Include installation via CDN in readme

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#39]
With #37 the user can install the library via CDN. This should be mentioned in the installation section of the readme.

Example CDN link: https://unpkg.com/@turingpointde/cvss.js@latest/dist/production.min.js

**Comment by MrDoomy** [comment]
Hi! 👋
I'd like to help, can you assign to me this issue?

**Comment by Fubinator** [comment]
Sure @MrDoomy!

**Comment by MrDoomy** [comment]
Hello again @Fubinator 👋
I just create at PR right now.
Let me know if it doesn't fit, I'll change that quickly 😉
