### ISSUE TITLE
Correct order of metrics for vector parsing

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#42]
When the users passes an object, whose entries are not in the correct order, the parsing of that object to a vector string returns  an invalid vector.

Example:
```js
const obj = {
  A: "N",
  AC: "L",
  AV: "N",
  C: "L",
  CVSS: "3.0",
  E: "X",
  I: "H",
  PR: "N",
  RC: "X",
  RL: "X",
  S: "U",
  UI: "N"
};

CVSS(obj) // Error: The vector format is not valid!
```

The constructed string is:
` A:N/AC:L/AV:N/C:L/CVSS:3.0/E:X/I:H/PR:N/RC:X/RL:X/S:U/UI:N`

But it should be:
`CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N/E:X/RL:X/RC:X`

This happens because we use `Object.entries` to iterate over the input object. If we somehow use the definitions from the json file (they are in the correct order) to iterate, it should be in the correct order.

**A note on this**: The specification only says that the vector must start with "CVSS:VERSION_NUMBER", the rest of the order does not matter. However, I think it is good style to construct the vector as a whole in the recommended order.

**Comment by RhnSaxena** [comment]
@Fubinator I want to take this issue. Please assign this to me. 
As I can see, the JSON file contains more `abbr` than mentioned in the example. So, should I expect that some of the inputs might not be having all the `abbr`?

**Comment by Fubinator** [comment]
Sure, go ahead @RhnSaxena.

Yes, exactly, not all metrics are mandatory. The example above is a good way to test the bevahiour.
