### ISSUE TITLE
Move version dependent functions to a separate file

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#43]
The `cvss.js` file is getting quite big. To implement #26 we should make sure we won't run into problems with different versions.

Since CVSS version 3.0 and 3.1 are very similar in terms of metrics and differ for the most part only in the calculations, all functions for calculating the scores should be in a separate file.

This should increase our ability to run tests more specifically by a lot  as well.

**Comment by pranshumaheshwari** [comment]
I can work on this

**Comment by Fubinator** [comment]
Yes, go 4 it @pranshumaheshwari if you have any questions feel free to ask.
