### ISSUE TITLE
Move vector utility functions to a separate file

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#44]
To keep the overview, some of our internal functions can be outsourced to a util file. Only version independent functions should be considered here. Some functions that came into my mind are `parseVectorObjectToString` and `isVectorValid`.

**Comment by pranshumaheshwari** [comment]
I can do this, if no one is working on it

**Comment by Fubinator** [comment]
Hey @pranshumaheshwari I think this one is currently taken by a colleague. You can have a look at #48 or #43, though.

**Comment by Fubinator** [comment]
Implemented with #51
