### ISSUE TITLE
Always return all metrics in getVectorObject function

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#48]
Currently only metrics defined in the vector string are returned in the getVectorObject function. This leads to problems as soon as the environmental score is to be calculated, for example. The function currently iterates over all metrics in the string, but it should instead iterate over all available metrics, add them to the object and take the values from the string.

Here is an example. The current behaviour is the following:
```js
const vector = CVSS("CVSS:3.0/AV:N/AC:H/PR:L/UI:R/S:C/C:L/I:L/A:L/E:U/RL:T/RC:R");

console.log(vector.getVectorObject()); // { CVSS: "3.0", AV: "N", AC: "H", PR: "L", UI: "R", S: "C", C: "L", I: "L", A: "L", E: "U", RL: "T", RC: "R" }
```

The function should instead return
`{ CVSS: "3.0", AV: "N", AC: "H", PR: "L", UI: "R", S: "C", C: "L", I: "L", A: "L", E: "U", RL: "T", RC: "R", CR: "X", IR: "X", AR: "X", MAV: "X", MAC: "X", MPR: "X", MUI: "X", MS: "X" , MC: "X", MI: "X", MA: "X"}`

**Comment by pranshumaheshwari** [comment]
I can work on this

**Comment by Fubinator** [comment]
Alright, go ahead @pranshumaheshwari 
If you have any questions feel free to ask.

**Comment by pranshumaheshwari** [comment]
The "X" is to be returned or say undefined is to be returned?
