### ISSUE TITLE
Add environmental score test to test if partial vectors work

### ISSUE THREAD

**Issue by Fubinator** [turingpointde/cvss.js#50]
As it is not necessary to define all metrics we need one test to check if the correct environmental score is calculated. There might be a bug over here.

The environmental score of the vector `CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N/E:P/RL:O/IR:M/MAV:A/MPR:N/MI:L` should be 4.9. [ref](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N/E:P/RL:O/IR:M/MAV:A/MPR:N/MI:L)

This vector should be added to the tests to make sure this works. If it does not work, we should look into fixing this.

**Comment by pranshumaheshwari** [comment]
According to [this](https://www.first.org/cvss/calculator/3.0#CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:H/A:N/E:P/RL:O/IR:M/MAV:A/MPR:N/MI:L) the score should be 8.2 and the output also is 8.2

**Comment by Fubinator** [comment]
You're looking at the base score. The environmental score (if you scroll down a little bit) is 4.9
